### PR TITLE
Avereha/golangci lint

### PR DESCRIPTION
**Pull request by avereha**
## What issue is this change attempting to solve?

Add golangci-lint in CI.

## How does this change solve the problem? Why is this the best approach?

Was following docs here: https://golangci-lint.run/usage/install/#ci-installation

## How can we be sure this works as expected?

Let's see if it does something when I open a PR. It does!
Will continue this after merging other PRs.

### CODE REVIEW

**Comment by grzkv** [comment]
We already have linting with the same toolset in our makefile. Wouldn't it be simpler to enable linting in already existing workflow instead of introducing a whole new one?

**Comment by avereha** [comment]
I followed advice from official documentation that is linked. Reasons listed in the docs:
```
We recommend using our GitHub Action for running golangci-lint in CI for GitHub projects. It's fast and uses smart caching inside and it can be much faster than the simple binary installation.
Also, the action creates GitHub annotations for found issues: you don't need to dig into build log to see found by golangci-lint issues:
```

**Comment by grzkv** [comment]
I am not sure the documentation applies in our case or is it for a case when you have only the linting in CI. 

The main upside I can see is speed-up. It is true that this kind of linting can be quite slow. We took care to make it reasonably fast but I frankly don't know the current state. If this workflow runs in parallel and linting takes majority of CI time, it makes sense.

**Review by grzkv — APPROVED** [review]

**Comment by avereha** [comment]
Moved it to the same workflow as a different step.
Also configured CI to run only on merge requests and push to master, so we don't have two running tests in parallel.

**Pull request merged**
