### PR TITLE
Avereha/errrors 2

### PR DESCRIPTION
**Pull request by avereha**
# What issue is this change attempting to solve?

Addressing this comment: https://github.com/bookingcom/carbonapi/pull/275#discussion_r465954831
When I pushed the previous change, we still had too many errors and it was not clear if we can treat all unknown errors as 'http 500' or not.

## How does this change solve the problem? Why is this the best approach?

Now that we cleaned up almost all errors, it's safer to say that remaining errors are just 'internal server error' 
Since I was editing that part, I also moved all the error reporting details in the 'writeError' function.

## How can we be sure this works as expected?
make test
tested with production traffic.

### CODE REVIEW

**Comment by grzkv** [comment]
Does this PR also include extrapolation besides error logic changes?

**Comment by grzkv** [comment]
Can it be that this PR also includes commits from other PRs? I see a lot of changes that are not errors-related.

**Comment by avereha** [comment]
yes, I have to rebase it.

**Comment by avereha** [comment]
Rebased!

**Pull request merged**
