### PR TITLE
Switch to go modules

### LINKED ISSUE #131: Migrate to go modules
Currently we use `dep` for dependency management. As it becomes deprecated in favor of `go modules`, we need to migrate as well.

### PR DESCRIPTION
**Pull request by paskal**
Should fix #131.
Build and tests are working, `system_test.sh` executed successfully: please point me to how to test this properly.

### CODE REVIEW

**Comment by grzkv** [comment]
Are you sure the libs in use all stay the same version?

**Comment by paskal** [comment]
All directly mentioned libs are the same version. The problem I see is the removal of the many vendored directories: let's include all possible build tags (and with -mod=vendor) in CI pipeline?

**Comment by grzkv** [comment]
I'd keep vendor for now.

**Comment by grzkv** [comment]
If we keep vendor we can have a much better vision about what has changed in the used libs. What do you think, @paskal ?

**Comment by paskal** [comment]
Done, moduels introduced and vendors are intact.

**Comment by azhiltsov** [comment]
vendor was introduces in order to have reproduceabe builds. We can remove them only in case if modules can provide us the same guarantees.

**Comment by paskal** [comment]
@azhiltsov, go modules can vendor dependencies as well but @grzkv is against introducing any changes to vendor folder (and go modules do introduce changes) so I left go.mod and didn't touch existing vendoring.
As I see the problem is the following: no one can be sure that some change leaves the project in working state and it even builds properly with build tag `cairo`. The only way to know for sure for now is to run it somewhere in production and see what happens. I hope #70 will fix that situation.

**Comment by paskal** [comment]
Modules introduced with minimal changes to vendored versions possible, please review. I haven't switched travis and all the code to using vendored versions, that would be a different issue to work on.

**Comment by grzkv** [comment]
Did you use any info from `dep` when migrating?

**Comment by paskal** [comment]
Yes, the **only** difference is `yaml.v2` 2.2.2 vs 2.2.1 original: it adds single new function and I didn't revert this bugfix version upgrade.

**Comment by grzkv** [comment]
I will take some time to reflect on this change. It looks good on first glance, but there may be some non-obvious discrepancies. Sorry that this is taking a bit longer.

**Comment by paskal** [comment]
@grzkv I've updated and re-checked everything once more and also added and tested vendoring for builds and tests. Everything works the same way it works now, libraries versions are the same.

**Comment by paskal** [comment]
@grzkv let's finally merge it?

**Comment by paskal** [comment]
@grzkv @azhiltsov let's merge this one?

**Comment by grzkv** [comment]
@paskal I will test this one following day or two.

**Comment by grzkv** [comment]
@paskal I will test this one tomorrow or day after.

**Comment by paskal** [comment]
@grzkv I believe you can do this!

**Comment by harudark** [comment]
I'm still tryig to figure out what's the best way to migrate to go modules with vendoring.
Because @grzkv wants to move forward this PR today, I share some of my thoughts here.


According to [this](https://blog.golang.org/migrating-to-go-modules),
> It is always good practice to run go mod tidy before committing a go.mod file to version control

I understand this PR is trying to introduce modules with minimal changes to vendored versions possible.
But if `go mod tidy` hasn't been run, I don't think go modules switching has been completed.

The problem is if we run `go mod tidy` right now, `gonum.org/v1/gonum` will upgrade to v0.6.2(released on 25 Dec 2019), which is a big change compared to the current version "20181001095203".

My suggestion is it's better to wait for #70 to fix and then move to go modules switching.

**Comment by paskal** [comment]
I agree that it's better to proceed with the switch when the project will really need it and will have enough confidence to do so rather than now. I am not willing to continue updating this branch and closing this PR.

**Pull request closed without merging**
