### PR TITLE
Support aggregation specifier symbol @ in metric names for mix aggregation policy

### PR DESCRIPTION
**Pull request by bom-d-van**
Hi, this is for supporting mix aggregation policy implemented for cwhisper and go-carbon.

Relevant PRs:
https://github.com/go-graphite/go-whisper/pull/5
https://github.com/lomik/go-carbon/pull/331/files

### CODE REVIEW

**Comment by grzkv** [comment]
I see that the support for this aggregation is a draft in `go-carbon`. Is this need now or is it for later?

**Comment by grzkv** [comment]
@bom-d-van ^^^

**Comment by grzkv** [comment]
@bom-d-van ^^^

**Comment by bom-d-van** [comment]
Hi @grzkv, sorry, just saw your message. Yeah, the changes in go-carbon is in draft. This is currently for early preview and it's pretty minor change. Had some discussions with @azhiltsov few weeks ago. 
Will come back here once we have the changes moved forward in go-carbon.

**Comment by grzkv** [comment]
I think it makes sense to wait until the changes to go-carbon are merged. I guess this PR requires that to happen to make sense.

**Pull request closed without merging**
