### PR TITLE
Fix builds without cairo

### PR DESCRIPTION
**Pull request by reyjrar**
I'm not a golang developer, but after a lot of fighting with the build,
I *think* this restores the option to build this without libcairo.

### CODE REVIEW

**Comment by grzkv** [comment]
@reyjrar The CI has to succeed before we have a look at this PR.

**Comment by blind-oracle** [comment]
@reyjrar You need to add a newline after the **// +build ** for it to work.

**Comment by grzkv** [comment]
On my machine the `nocairo` build works even without these changes.

On the first glance, it makes sense to exclude the compilation of the `pixel_ratio` when *cairo* tag is absent. But there may be deeper implications.

**Comment by blind-oracle** [comment]
@grzkv *nocairo* build works if you have cairo lib present and links it anyway because `pixel_ratio.go` imports `github.com/evmar/gocairo/cairo` which is cgo.

I don't think that there are any implication in not building `pixel_ratio.go` if nothing except cairo-related stuff depends on it. And if there were anything then carbonapi would not have built without it.

**Comment by reyjrar** [comment]
I'm building using mock, so it's a pristine environment every run and libcairo and friends are not around.  I'm building this for CentOS 6, where the cairo version doesn't meet the minimum cairo version required.

**Comment by koorgoo** [comment]
Checked the PR on CentOS 6 - it worked.

**Pull request merged**
