### PR TITLE
lint: use golangci-lint, initial project config

### PR DESCRIPTION
**Pull request by jwkohnen**
I tried to create a meaningful project local config in .golangci.yml, but of
course this is a matter of taste and debate.  Most of the settings come from
the default golangci-lint config file.

As of now golangci-lint finds quite a bunch of issues.  IMHO they're all worth
investigating.  I have explicitly exluded "composite literal uses unkeyed
fields" in test files as this style is used widely in the table driven tests.

The invocation via make shows only issues that are introduced since the
merge-base of this commit on the master branch in order to make the
introduction painless in CI pipelines etc.

/fixes: #189

### CODE REVIEW

**Comment by grzkv** [comment]
I am not sure we can include this in Travis CI now since linting will always fail. Successful Travis run is currently required for PR merge.

**Comment by jwkohnen** [comment]
Yeah, I figured after seeing it fail, because the binary is not available. We could integrate it into GitHub via https://golangci.com/ which may be favourable anyway. I could move the `--new-from-rev` into the `.golangci.yml` and create a special Makefile target which "reports all the gore".

**Comment by grzkv** [comment]
Let's just remove it from the Travis for now and make an issue to do that in the future. How about that?

**Comment by grzkv** [comment]
> a special Makefile target which "reports all the gore"
This makes sense.

**Comment by ksurent** [comment]
golangci-lint vendors a fairly old version of staticcheck (from Jan 2019). I think we should disable the vendored version and run the latest standalone. If we do that, we should also revisit other linters enabled in golangci-lint because they may overlap.

**Comment by jwkohnen** [comment]
squashed. There are now two make targets: lint and lint-all. The first uses the current merge-base as baseline, the latter shows everything. Travis does not use golangci-lint, yet. I'll create follow-up issues for Travis and for using a newer staticcheck.

**Pull request merged**
